// GET /api/compliance/policy-document — Download AI Use Policy document
import { NextResponse } from 'next/server';
const { getDb } = require('@/lib/db');
const { requireAdmin } = require('@/lib/auth');

export async function GET(request) {
  try {
    const auth = await requireAdmin(request);
    if (auth.error) return NextResponse.json({ error: auth.error }, { status: auth.status });

    const db    = getDb();
    const orgId = auth.user.orgId;

    const org     = db.prepare('SELECT name, domain FROM orgs WHERE id = ?').get(orgId);
    const members = db.prepare('SELECT email, role FROM users WHERE org_id = ? ORDER BY role DESC, email ASC').all(orgId);
    const policy  = db.prepare('SELECT rules FROM policies WHERE org_id = ? LIMIT 1').get(orgId);
    const ts      = new Date().toISOString();
    const date    = ts.split('T')[0];

    const orgName = org?.name || org?.domain || 'Your Organisation';

    // Parse policy rules to build prohibited data section
    let rules = {};
    try { rules = JSON.parse(policy?.rules || '{}'); } catch { /* use defaults */ }

    const DATA_TYPE_LABELS = {
      EMAIL:        'Email addresses',
      PHONE:        'Phone numbers',
      IBAN:         'Bank account numbers (IBAN)',
      CREDIT_CARD:  'Credit and debit card numbers',
      ADDRESS:      'Physical addresses',
      PASSWORD:     'Passwords, API keys, and credentials',
      NATIONAL_ID:  'National identity numbers and passport numbers',
      VAT:          'VAT and tax identification numbers',
      IP_ADDRESS:   'Internal IP addresses',
      DATE_OF_BIRTH:'Dates of birth',
    };

    const blocked = [];
    const warned  = [];
    for (const [type, action] of Object.entries(rules)) {
      if (action === 'BLOCK' && DATA_TYPE_LABELS[type]) blocked.push(DATA_TYPE_LABELS[type]);
      if (action === 'WARN'  && DATA_TYPE_LABELS[type]) warned.push(DATA_TYPE_LABELS[type]);
    }

    const lines = [];

    lines.push(`AI USE POLICY`);
    lines.push(`=============`);
    lines.push(``);
    lines.push(`Organisation: ${orgName}`);
    lines.push(`Effective date: ${date}`);
    lines.push(`Generated by: PromptFence (promptfence.ai)`);
    lines.push(`Document version: 1.0`);
    lines.push(``);
    lines.push(`─────────────────────────────────────────────────────────────────`);
    lines.push(``);

    lines.push(`1. PURPOSE`);
    lines.push(`----------`);
    lines.push(`This policy governs the use of artificial intelligence (AI) tools and large language`);
    lines.push(`model (LLM) services by employees, contractors, and agents of ${orgName}.`);
    lines.push(``);
    lines.push(`It establishes mandatory controls to prevent the exposure of sensitive and personal`);
    lines.push(`data through AI tools, and to meet obligations under the EU AI Act, GDPR, and`);
    lines.push(`applicable information security frameworks.`);
    lines.push(``);

    lines.push(`2. SCOPE`);
    lines.push(`-------`);
    lines.push(`This policy applies to:`);
    lines.push(`  - All employees, contractors, and third parties with access to company systems`);
    lines.push(`  - All AI tools accessed via browser (ChatGPT, Claude, Gemini, Copilot, etc.)`);
    lines.push(`  - All AI capabilities accessed via API or integrated into company products`);
    lines.push(`  - All devices and networks used to conduct company business`);
    lines.push(``);

    lines.push(`3. APPROVED AI TOOLS`);
    lines.push(`--------------------`);
    lines.push(`The list of approved AI tools is maintained in the PromptFence compliance dashboard`);
    lines.push(`and reviewed at least quarterly. Using an AI tool not on the approved list is`);
    lines.push(`prohibited for processing company or customer data.`);
    lines.push(``);
    lines.push(`Employees who wish to use a new AI tool must request approval from the designated`);
    lines.push(`AI governance contact before use with any company or customer data.`);
    lines.push(``);

    lines.push(`4. PROHIBITED DATA`);
    lines.push(`------------------`);
    lines.push(`The following categories of data must NOT be submitted to any AI tool.`);
    lines.push(`Automatic blocking is enforced by PromptFence where technically possible.`);
    lines.push(``);
    if (blocked.length > 0) {
      lines.push(`BLOCKED (submission prevented automatically):`);
      for (const item of blocked) lines.push(`  - ${item}`);
    } else {
      lines.push(`BLOCKED (submission prevented automatically):`);
      lines.push(`  - Bank account numbers (IBAN)`);
      lines.push(`  - Credit and debit card numbers`);
      lines.push(`  - Passwords, API keys, and credentials`);
      lines.push(`  - National identity numbers and passport numbers`);
    }
    lines.push(``);
    if (warned.length > 0) {
      lines.push(`RESTRICTED (requires employee judgement — warning issued):`);
      for (const item of warned) lines.push(`  - ${item}`);
    } else {
      lines.push(`RESTRICTED (requires employee judgement — warning issued):`);
      lines.push(`  - Email addresses of customers, employees, or third parties`);
      lines.push(`  - Phone numbers`);
      lines.push(`  - Physical addresses`);
    }
    lines.push(``);
    lines.push(`In all cases, the employee must consider whether submitting data to an AI tool is`);
    lines.push(`necessary and proportionate for the task at hand.`);
    lines.push(``);

    lines.push(`5. PERMITTED USES`);
    lines.push(`-----------------`);
    lines.push(`AI tools may be used for the following purposes, provided no prohibited data`);
    lines.push(`categories are included in prompts or uploaded files:`);
    lines.push(``);
    lines.push(`  - Drafting, editing, and summarising non-sensitive documents`);
    lines.push(`  - Writing and reviewing code that does not contain credentials or customer data`);
    lines.push(`  - Research, ideation, and brainstorming`);
    lines.push(`  - Translation and language assistance`);
    lines.push(`  - Internal knowledge base queries on approved platforms`);
    lines.push(``);

    lines.push(`6. EMPLOYEE OBLIGATIONS`);
    lines.push(`-----------------------`);
    lines.push(`All employees must:`);
    lines.push(``);
    lines.push(`  a) Install the PromptFence browser extension before using any AI tool`);
    lines.push(`     on a company device or for company purposes`);
    lines.push(``);
    lines.push(`  b) Acknowledge this policy in the PromptFence dashboard`);
    lines.push(``);
    lines.push(`  c) Review and act on any warning alerts before proceeding with a prompt`);
    lines.push(``);
    lines.push(`  d) Report any suspected data exposure incidents to the data protection`);
    lines.push(`     contact immediately`);
    lines.push(``);
    lines.push(`  e) Not attempt to circumvent, disable, or work around any PromptFence controls`);
    lines.push(``);

    lines.push(`7. MONITORING AND LOGGING`);
    lines.push(`-------------------------`);
    lines.push(`${orgName} uses PromptFence to monitor AI tool usage in accordance with applicable law.`);
    lines.push(`The following information is logged for each AI interaction:`);
    lines.push(``);
    lines.push(`  - Timestamp, user, and AI platform accessed`);
    lines.push(`  - Categories of sensitive data detected (not the data itself)`);
    lines.push(`  - Action taken (allowed, warned, blocked)`);
    lines.push(``);
    lines.push(`Detection is performed locally in the browser. Prompt content is never transmitted`);
    lines.push(`to PromptFence servers. Only metadata (data type, action, platform) is stored.`);
    lines.push(``);
    lines.push(`Logs are retained for 12 months and may be used in the event of a data protection`);
    lines.push(`investigation or audit.`);
    lines.push(``);

    lines.push(`8. INCIDENT RESPONSE`);
    lines.push(`--------------------`);
    lines.push(`If an employee believes sensitive data has been submitted to an AI tool:`);
    lines.push(``);
    lines.push(`  1. Stop using the AI tool immediately`);
    lines.push(`  2. Do not attempt to delete or modify any evidence`);
    lines.push(`  3. Report the incident to privacy@${org?.domain || 'yourcompany.com'} within 1 hour`);
    lines.push(`  4. Preserve any relevant conversation history for review`);
    lines.push(``);
    lines.push(`The Data Protection Officer will assess whether GDPR Art. 33 notification is required.`);
    lines.push(``);

    lines.push(`9. COMPLIANCE REFERENCES`);
    lines.push(`------------------------`);
    lines.push(`This policy is designed to satisfy the following regulatory and framework requirements:`);
    lines.push(``);
    lines.push(`  EU AI Act`);
    lines.push(`    Art. 4  — AI literacy obligations for deployers`);
    lines.push(`    Art. 10 — Data governance and AI tool inventory`);
    lines.push(`    Art. 12 — Record-keeping and logging requirements`);
    lines.push(`    Art. 14 — Human oversight measures`);
    lines.push(``);
    lines.push(`  GDPR (EU) 2016/679`);
    lines.push(`    Art. 5  — Principles of data processing (purpose limitation, minimisation)`);
    lines.push(`    Art. 25 — Data protection by design and by default`);
    lines.push(`    Art. 32 — Security of processing`);
    lines.push(``);
    lines.push(`  ISO 27001:2022`);
    lines.push(`    A.5.1  — Policies for information security`);
    lines.push(`    A.5.10 — Acceptable use of information and assets`);
    lines.push(`    A.6.3  — Information security awareness and training`);
    lines.push(`    A.8.16 — Monitoring activities`);
    lines.push(`    A.8.22 — Filtering of web services`);
    lines.push(``);
    lines.push(`  SOC 2 (AICPA Trust Services Criteria)`);
    lines.push(`    CC6.1  — Logical and physical access controls`);
    lines.push(`    CC6.3  — Access to data`);
    lines.push(`    CC6.7  — Data transmission controls`);
    lines.push(`    CC7.2  — System monitoring`);
    lines.push(``);

    lines.push(`10. REVIEW AND ENFORCEMENT`);
    lines.push(`--------------------------`);
    lines.push(`This policy is reviewed at least annually, or following any material change in`);
    lines.push(`the organisation's AI tool usage or applicable regulatory requirements.`);
    lines.push(``);
    lines.push(`Violations of this policy may result in disciplinary action up to and including`);
    lines.push(`termination of employment or engagement, and may be reported to the relevant`);
    lines.push(`supervisory authority.`);
    lines.push(``);
    lines.push(`─────────────────────────────────────────────────────────────────`);
    lines.push(``);
    lines.push(`Policy owner: ${orgName}`);
    lines.push(`Next review date: ${new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]}`);
    lines.push(`Generated: ${ts}`);
    lines.push(`Document generated by PromptFence — promptfence.ai`);

    const content  = lines.join('\n');
    const filename = `ai-use-policy-${orgName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${date}.txt`;

    return new NextResponse(content, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error('Policy document error:', error);
    return NextResponse.json({ error: { code: 'INTERNAL_ERROR', message: 'Server error' } }, { status: 500 });
  }
}
